#!/usr/bin/env perl

use LeafyWeb::LeafyD::Entry;
use LeafyWeb::LeafyD::HandlerRegistry;

# clean up!
use strict;

my $file_name = $ARGV[0];

# make sure we have a file name
unless ($file_name) {
    print "FAILED:no file name specified!\n";
    exit();
}


# create the entry object for this piece of data.
my $entry;
# catch errors
eval {
    $entry = LeafyWeb::LeafyD::Entry->new($file_name);
};

if (my $error = $@) {
    if ($error =~ /[\r\n]+$/) {
        print "FAILED:entry creation error $error";
    } else {
        print "FAILED:entry creation error $error\n";
    }
    exit();
}

#
# real handler starts here
#

$entry->completed;
print "PASSED:entry finished processing\n";
